<a href="https://colab.research.google.com/github/umiSirya/Python-Data-Analysis/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy


In [3]:
import numpy as np
np.__version__
np?

In [6]:
x = [1,2,3,4]
print(type(x))

x = np.array(x)
print(type(x))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
list_1D = [1,2,3,4]
list_2D = [[1,2,3,4]]
list_3D = [[[1,2,3,4]]]

array_3D=np.array(list_3D)
print(array_3D)

[[[1 2 3 4]]]


In [11]:
list=[1,2,'Naomi']
array= np.array(list)
print(array)

arr = np.arange(10)
print(arr)
print(type(arr))

['1' '2' 'Naomi']
10
<class 'numpy.ndarray'>


In [14]:
arr = np.arange(2,10)
print(arr)
print(type(arr))

[2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [15]:
arr = np.arange(2,10,2)
print(arr)
print(type(arr))

[2 4 6 8]
<class 'numpy.ndarray'>


In [18]:
arr = np.linspace(1,4,6)
print(arr)
print(type(arr))

[1.  1.6 2.2 2.8 3.4 4. ]
<class 'numpy.ndarray'>


In [ ]:
arr = np.arange(4,3,3),3
print(arr)
print(type(arr))

[2 4 6 8]
<class 'numpy.ndarray'>


In [22]:
#Generates numbers between 0 and 1
arr = np.random.random((2,4))
print(arr)
print(type(arr))

#Generates whole numbers
arr = np.random.randint((2,4))
print(arr)
print(type(arr))

[[0.70831549 0.11851684 0.19132337 0.52471948]
 [0.06911138 0.67593428 0.54081789 0.47195312]]
<class 'numpy.ndarray'>
[0 2]
<class 'numpy.ndarray'>


In [23]:
np.array([1,2,5])

array([1, 2, 5])

In [24]:
mat = np.array([[[1,2,3],[3,4,5],[6,7,8]]], dtype=int)
print(mat)

[[[1 2 3]
  [3 4 5]
  [6 7 8]]]


In [26]:
print('No of Dimensions',mat.ndim)
print('/n')

No of Dimensions 3
/n


In [29]:
int_arr = np.array([1,2,3], dtype=np.int32)
print(int_arr)
print(type(int_arr))
print(type(int_arr.dtype))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.dtypes.Int32DType'>


In [30]:
float_arr = np.array([1,2,3], dtype=np.int32)
print(float_arr)
print(type(float_arr))
print(type(float_arr.dtype))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.dtypes.Int32DType'>


In [31]:
bool_arr = np.array([True,False,True], dtype=bool)
print(bool_arr)
print(type(bool_arr))
print(type(bool_arr.dtype))

[ True False  True]
<class 'numpy.ndarray'>
<class 'numpy.dtypes.BoolDType'>


In [32]:
complex_arr = np.array([1+2j,3-4j], dtype=np.complex128)
print(complex_arr)
print(type(complex_arr))
print(type(complex_arr.dtype))

[1.+2.j 3.-4.j]
<class 'numpy.ndarray'>
<class 'numpy.dtypes.Complex128DType'>


In [36]:
arr =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)
print(arr)

arr2=arr.reshape(5,2)
arr2

(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [38]:
#flattens the the array into 1D array
arr3=arr.reshape(-1)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
#creates a row vector
arr5=arr.reshape(1,-1)
arr5

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
#creaTES a column vector
arr5=arr.reshape(-1,1)
arr5